"""empty message

Revision ID: 91113cbe71e3
Revises: cebae6799f5b
Create Date: 2026-03-01 22:51:19.859078

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91113cbe71e3'
down_revision = 'cebae6799f5b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicles_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['characters_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles_id'], ['id'])

    with op.batch_alter_table('learn_more', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characters_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('vehicles_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['characters_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('learn_more', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicles_id')
        batch_op.drop_column('planets_id')
        batch_op.drop_column('characters_id')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('vehicles_id')
        batch_op.drop_column('planets_id')
        batch_op.drop_column('characters_id')

    # ### end Alembic commands ###
